### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by robinst** [jtbandes/space-pics#1]
Hi!

I've found this repository via [your StackOverflow answer](https://stackoverflow.com/a/64110231/305973). The [ZoomableScrollView](https://github.com/jtbandes/SpacePOD/blob/main/SpacePOD/ZoomableScrollView.swift) looks to be the best-working solution I've found so far for a nice zoomable image view!

So I'd like to reuse it. But I haven't seen a license file or header anywhere, so not sure what license this code is under. It would be good if you could clarify!

GitHub has a license chooser here: https://github.com/jtbandes/SpacePOD/community

(I personally like MIT for its simplicity and openness. But of course it's your choice!)

**Comment by jtbandes** [comment]
Thanks for your interest! Just added the MIT license. I'd love to hear what you end up making with it!
